name: Error Resolution — n8n Repos
description: Resolve build, dependency, and secret issues
labels: ["bug","triage","n8n"]
body:
  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      options:
        - label: Update Node LTS. Deduplicate packages. Recreate lock
        - label: CI uses setup-node LTS. Cache npm. Lint workflows JSON
        - label: Normalize using workflow snapshots if present
        - label: Replace inline tokens with env refs. Rotate keys. Add .env.example
        - label: Schema validate and dry import to test n8n